### PR TITLE
Add a have-quartz-gtk flag for gtk3

### PR DESCRIPTION
**Pull request by taqenoqo**
Add have-quartz-gtk flag to gtk3 as well as gtk for #274.

### CODE REVIEW

**Comment by int-index** [comment]
I have confirmed locally that this indeed fixes #274, which I'm facing after the `brew` formula for `gtk+` updated from `3.24.9` to `3.24.10`.

NB. This fix requires `echo "constraints:\n  gtk3 +have-quarts-gtk" >> cabal.project.local` to take effect.

@hamishmack Would you mind merging and making a new minor release?

**Comment by int-index** [comment]
ping @hamishmack

**Comment by hamishmack** [comment]
With Gtk 3 we should be able to use [GDK_WINDOWING_QUARTZ](https://developer.gnome.org/gdk3/stable/gdk3-General.html#GDK-WINDOWING-QUARTZ:CAPS). It seems like it should be doing just that [here](https://github.com/gtk2hs/gtk2hs/blob/ffc9b55f469aab1beb8d3cccb05df0471710b012/gtk/Graphics/UI/Gtk/General/Structs.hsc#L634).

Perhaps there is problem with the brew installed Gtk 3.   Can you please check that `GDK_WINDOWING_QUARTZ` is defined?  When installed with nix the `GDK_WINDOWING_QUARTZ` is defined in `include/gtk-3.0/gdk/gdkconfig.h`.

**Comment by int-index** [comment]
```
$ cat /usr/local/Cellar/gtk+3/3.24.10/include/gtk-3.0/gdk/gdkconfig.h
#ifndef __GDKCONFIG_H__
#define __GDKCONFIG_H__

#if !defined (__GDK_H_INSIDE__) && !defined (GDK_COMPILATION)
#error "Only <gdk/gdk.h> can be included directly."
#endif

#include <glib.h>

G_BEGIN_DECLS


#undef GDK_WINDOWING_X11
#undef GDK_WINDOWING_BROADWAY
#undef GDK_WINDOWING_WAYLAND
#undef GDK_WINDOWING_WIN32

G_END_DECLS

#endif  /* __GDKCONFIG_H__ */
```

**Comment by hamishmack** [comment]
Looks like [this](https://gitlab.gnome.org/GNOME/gtk/merge_requests/1004) might be related.

**Comment by hamishmack** [comment]
I'm closing this as I am fairly certain the upstream issue has been (or will be) fixed and it is better not to have a flag to work around it here.  Please let me know if I am mistaken.

**Pull request closed without merging**
