### PR TITLE
Support GHC 9.8

### PR DESCRIPTION
**Pull request by Bodigrim**
I've also added CI as a witness that the packages build with GHC 9.8. The CI uncovered some unrelated minor issues with package bounds, fixed in separate commits.

### CODE REVIEW

**Comment by andreasabel** [comment]
@hamishmack: Friendly ping.
A successful CI run is available at: https://github.com/Bodigrim/gtk2hs/actions/runs/7432766003
CI will run here once merged into `master`.

**Comment by andreasabel** [comment]
@Bodigrim I tried to build from this PR, but failed.  Took me a while to realize why: https://github.com/gtk2hs/gtk2hs/blob/6ebffd4b84716f056b07ac70df45721e5f1ee450/cabal.project#L1
I think this PR should include a removal of this line with nails the hackage snapshot, and thus prevents picking up `vecto-0.13.1`.
Haskell CI works by accident here because it simply ignore the `cabal.project` file...

**Comment by Bodigrim** [comment]
@andreasabel done.

**Review by andreasabel — APPROVED** [review]
Thanks!

**Comment by Bodigrim** [comment]
@hamishmack any chance to merge this please?

**Comment by Bodigrim** [comment]
@hamishmack yet another ping.

**Comment by Bodigrim** [comment]
@hamishmack can we move forwards with this somehow? Or is there any other maintainer who can merge this?

**Comment by andreasabel** [comment]
@hamishmack Ping.
@ocharles Maybe merge, since the essence of this PR is already published as revisions.

**Pull request merged**
